### ISSUE TITLE
Strange behavior - charger getting enabled without trigger

### ISSUE THREAD

**Issue by zierbeek** [dan-r/HomeAssistant-Ohme#84]
**What happened?**
The charger is turning on without it's receiving a trigger. this could however be related to the way my automation is setup. It turned on at 1am in the night without the automation being fired.

**Expected behavior**
The average solar excess should trigger the start of the charge. When the excess goes below 2, it should turn it off.

**automation**
```yaml
alias: Charger Control Based on Solar Surplus
description: Control Ohme charger based on solar surplus
trigger:
  - platform: state
    entity_id: binary_sensor.ohme_car_connected
    to: "on"
  - platform: state
    entity_id: binary_sensor.ohme_car_connected
    to: "off"
  - platform: numeric_state
    entity_id:
      - sensor.AverageSolarExcess
    above: 2.2
    id: PV++
  - platform: numeric_state
    entity_id:
      - sensor.AverageSolarExcess
    below: 2
    id: PV--
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.ohme_car_connected
            state: "off"
        sequence:
          - service: switch.turn_on
            entity_id: switch.ohme_pause_charge
        alias: Pause charging on plug out
      - conditions:
          - condition: trigger
            id:
              - PV--
          - condition: state
            entity_id: binary_sensor.ohme_car_connected
            state: "on"
        sequence:
          - service: switch.turn_on
            entity_id: switch.ohme_pause_charge
        alias: Pause charging if solar surplus is low
      - conditions:
          - condition: trigger
            id:
              - PV++
        sequence:
          - service: switch.turn_off
            entity_id: switch.ohme_pause_charge
          - service: switch.turn_on
            entity_id: switch.ohme_max_charge
        alias: Resume charging if enough PV surplus
    default:
      - service: switch.turn_on
        entity_id: switch.ohme_pause_charge
```

**Log Output**
<img width="604" alt="Schermafbeelding 2024-07-08 om 20 55 07" src="https://github.com/dan-r/HomeAssistant-Ohme/assets/58994651/1c4261c1-973e-48c7-8841-fb0fb8ac7678">

**Home Assistant Version**
2024.5.5

**Integration Version**
V0.8.3.
